version: '3'
services:
  asr-eval:
    # stdin_open: true
    # tty: true
    image: openaudiosearch/asr-eval:0.1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - STAGE=0
      - ASR_NNET_DIR=exp/vosk-model-de-0.21
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities:
              - gpu
